import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Footer from "../components/layout/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "E-learning Platform",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://flyonui.becdn.net/pro/css/flyonui.css"
          rel="stylesheet"
        />
        <script src="https://flyonui.becdn.net/pro/libs/flyonui/flyonui.js"></script>
        <script src="https://flyonui.becdn.net/pro/libs/apexcharts/dist/apexcharts.min.js"></script>
        <script src="https://flyonui.becdn.net/pro/libs/lodash/lodash.min.js"></script>
        <script src="https://flyonui.becdn.net/pro/libs/flyonui/dist/helper-apexcharts.js"></script>
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
